name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install lint modules
      run: yarn install --frozen-lockfile

    - name: Run eslint
      run: yarn lint

    - name: Run eslint for tests
      run: yarn lint-tests
